<?php
/*
* Functions for the theme
* Code generated by Jeroen Martens at http://www.hieronymusdesign.nl
*/

/* Register Boostrap Navigation Walker */
require_once('includes/wp_bootstrap_navwalker/wp_bootstrap_navwalker.php');

/* Enable Support for Post Thumbnails  */
add_theme_support( 'post-thumbnails' );

/* Enable Support for Wordpress Menus */
add_theme_support( 'menus' );

	/* Register navigation menu */
	register_nav_menus( array( 'primary' => __( 'Primary Menu', 'THEMENAME' ),) );
	register_nav_menus( array( 'footer1' => __( 'Footer One', 'THEMENAME' ),) );
	register_nav_menus( array( 'footer2' => __( 'Footer Two', 'THEMENAME' ),) );
	register_nav_menus( array( 'footer3' => __( 'Footer Three', 'THEMENAME' ),) );

/* Enable Woocommerce support */
add_theme_support( 'woocommerce' );




?>